covid/views.py
# :filename: covid/views.py
#   views of flask_covid project / covid application
#
# marks:   #?      something to discover
#          #<      make attention; probably: remove this line

# std libs import
from datetime import datetime, date, timedelta
from io       import StringIO
from math     import ceil

# 3rd parties libs import
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for,
    current_app
)
from werkzeug.exceptions import abort
from flask_babel import _
from flask_babel import lazy_gettext as _l
from flask_babel import get_locale
from matplotlib.figure import Figure
import matplotlib.pyplot as plt

import bs4    as bs
import numpy  as np
import pandas as pd

# application libs import
from . import models
from . import forms


bp = Blueprint('views', __name__)

# here we go
THRESHOLD = 200
THRESHOLD_RATIO = 0.05


# ldfa,2020-10-03 remark: max 10 colors. not good for EU
COLORS=['tab:blue',
        'tab:orange',
        'tab:green',
        'tab:red',
        'tab:purple',
        'tab:brown',
        'tab:pink',
        'tab:gray',
        'tab:olive',
        'tab:cyan']

FIRST     = ''     # this placeholder to register the 1st day available ...
LAST      = ''     #   ... and this to hold the last day available
POP_FIELD = ''     # placeholder to register the population field name
EU_NUM = 10        # placehoder

@bp.before_request
def before_request():
    '''open data when request starts'''
    global FIRST
    global LAST
    global POP_FIELD
    global EU_NUM
    current_app.logger.debug('> before_request()')
    g.locale = str(get_locale())
    df = models.open_df(current_app.config['DATA_DIR']+'/'+current_app.config['DATA_FILE'],
                        pd.read_csv,
                        models.world_shape)                     # stores dataframe in g.df
    FIRST, LAST = (df['dateRep'].min(), df['dateRep'].max(),)
    #g.nations = models.Nations(dataframe=df)  # - ldfa, 2020-10-01 passing to models.GeoEntities
    g.first_date = df['dateRep'].min()
    g.last_date = df['dateRep'].max()
    POP_FIELD = current_app.config['POP_FIELD'][:]
    EU_NUM = current_app.config['EU_NUM']


@bp.teardown_request
def teardown_request(error=None):
    '''close data after request
    
    params: error         error - use str(error) to print
    '''

    current_app.logger.debug('> teardown_request({})'.format(error))
    models.close_df(error)
    if error:
        current_app.logger.error(str(error))      # Log the error


@bp.route('/')
@bp.route('/index')
@bp.route('/index.html')
def index():
    '''section's home'''
    
    fname = 'select'
    current_app.logger.debug('> {}()'.format(fname))
    how_many = g.df['countriesAndTerritories'].drop_duplicates().count()
    
    return render_template('index.html', 
                           title=_("Covid: time trend analysis"), 
                           #NATIONS=nations.get_for_list(), 
                           FIRST=FIRST,
                           LAST =LAST,
                           HOW_MANY=how_many
                          )

#< ldfa,2020-10-04 do we need to review this one due to the use of form.process()?
#<     see other_select()
@bp.route('/select', methods=['GET', 'POST'])
def select():
    '''select what country's trend to show'''
    
    fname = 'select'
    current_app.logger.debug('> {}() by {} http method'.format(fname, request.method))
    
    form = forms.SelectForm()
    
    # builds MAIN fields selection, i.e. [(1, 'cases',), ...]
    mkeys = forms.list_delta_fields(direct=False)
    form.mfields.choices = list(zip([forms.FIELDS[key]['id'] for key in mkeys], mkeys))

    # builds SECONDARY fields selection, i.e. [(1, 'cases',), ...]
    skeys = forms.list_delta_fields(direct=True)
    form.sfields.choices = list(zip([forms.FIELDS[key]['id'] for key in skeys], skeys))
    
    #form.fields.default = ['1',] # to set a default, this does not work;
                                  #    we use the "default" parameter in the class;
                                  #    alternatively we can set data (see below)
    
    #form.context.choices = [('nations','nations',), ('continents', 'continents',),]
    form.context.choices = list(zip(models.CONTEXT_SELECT, models.CONTEXT_SELECT))
    
    # builds continents selection: [('Africa', 'Africa',), ...] + [('North_America', 'North America',), ...]
    # - ldfa,2020.09.25 using models.GeoEntities instead of g.nations
    #form.continents.choices = [ (c, c, ) for c in g.nations.keys()]
    #form.continents.choices.extend( [ (c, c, ) for c in models.AREAS.keys() if models.AREAS[c]['context']=='continents'] )
    n = models.GeoEntities(attribute='type', value='nation')             # countries
    c = models.GeoEntities(attribute='type', value='continent')             # continents
    form.continents.choices = list(c.get_list_of_keys_names())
    form.continents.choices.sort(key=lambda x: x[1])                           # sort by name
    continents = [continent for continent in c.get_entities_att('name').values()]       # this is used in render_template
    nations    = [country for country in n.get_entities_att('name').values()]       # this is used in render_template
    
    # - ldfa,2020.09.25 using models.GeoEntities instead of g.nations
    #form.countries.choices = g.nations.get_for_select()
    #form.countries.choices.extend( [ (v['geoId'], c, ) for c, v in models.AREAS.items() if models.AREAS[c]['context']=='nations'] )
    n = models.GeoEntities(attribute='type', value='nation')             # nations
    form.countries.choices = list(n.get_list_of_keys_names())
    form.countries.choices.sort(key=lambda x: x[1])            # sort by name

    if request.method=='POST':
        time_range1 = forms.Range(FIRST, LAST)   #+- ldfa fix bug #2 initializing TimeRange for POST
        form.first.validators.append(time_range1)    #+-
        form.last.validators.append(time_range1)     #+-

    if form.validate_on_submit():

        # check context: nations or continents
        context = form.context.data[:]
        if context == 'nations':
            ids = '-'.join(form.countries.data)             # here build string with nations ids: e.g. it-fr-nl
        elif context == 'continents':
            ids = '-'.join(form.continents.data)             # here build string with continents ids: e.g. Asia-Europe
        else:
            raise ValueError(_('%(function)s: %(context)s is not a valid context', function='select', context=context))
            
        # chaining names of fields to plot i.e.: 'cases-deaths-cases/day-\N{Greek Capital Letter Delta}cases/day'
        mcolumns = [forms.FIELDS[name]['sid'] for name in forms.FIELDS.keys() if forms.FIELDS[name]['id'] in form.mfields.data ]
        scolumns = [forms.FIELDS[name]['sid'] for name in forms.FIELDS.keys() if forms.FIELDS[name]['id'] in form.sfields.data ]
        all_columns = mcolumns + scolumns
        columns = '-'.join(all_columns)
        
        first = form.first.data
        last  = form.last.data
        remember = form.remember.data
        
        # type of values: normal or normalized
        normalize = form.ratio_to_population.data
        #normalize = False
        overlap   = False
        
        form.first.validators.remove(time_range1)  # fix bug #2: we need to remove timerange validators to destroy them
        form.last.validators.remove(time_range1)   #    otherwise they will be reused in succedings calls
        
        return redirect(url_for('views.draw_graph', 
                                context=context, 
                                ids=ids, 
                                fields=columns, 
                                normalize=normalize, 
                                overlap=overlap,
                                first=first,
                                last=last,
                                remember=remember
                               )
                       )
    
    try:                                           # again: removing timerange validators. see previous comment
        if time_range1 in form.first.validators:
            form.first.validators.remove(time_range1)
        if time_range1 in form.last.validators:
            form.last.validators.remove(time_range1)
    except:
        pass

    #form.fields.data = ['1']                            # this sets a default value # WRONG: ldfa,2020-10-04 see below about "How to dynamically ..."
    form.first.data = FIRST # and this sets a default date
    form.last.data  = LAST
    #current_app.logger.debug('= {} - form.first.data: {}'.format(fname, form.first.data))
    #current_app.logger.debug('= {} - form.last.data: {}'.format(fname, form.last.data))
    
    # + ldfa,2020-10-04
    #< is it necessary to review the time validators behavior?
    # next by https://stackoverflow.com/questions/31423495/how-to-dynamically-set-default-value-in-wtforms-radiofield
    # about "How to dynamically set default value in WTForms RadioField?". This is valid even for integer fields
    # after a form.field.default=nn
    #form.process()
    
    
    return render_template('select.html', 
                           title=_('Select country'), 
                           main_fields=forms.dict_delta_fields(direct=False),
                           secondary_fields=forms.dict_delta_fields(direct=True),
                           form=form,
                           nations=nations,
                           continents=continents
                          )

@bp.route('/other_select', methods=['GET', 'POST'])
def other_select():
    '''other_select address: shows some precostituited queries to selct from a form'''
    
    fname = 'other_select'
    current_app.logger.debug('{}() using {} http method'.format(fname, request.method))
    
    # NOT READY
    #return 'Sorry. World select is not implemented yet. We will fix it soon.'

    # FROM HERE we go

covid/templates/base.html
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>ldfa | {{ _('Analizing data about Covid-19') }}</title>
        {% endif %}
        
        <meta http-equiv="content-language” content=”en”>
        
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
        
        <!-- warning: use 'url_for' to get static resources, otherwise it could fail on some template(s) -->
        <link rel="stylesheet" media="screen" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

        <link rel="icon" type="static/images/ico" href="{{ url_for('static', filename='images/favicon.ico') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/pygments.css') }}">
        
        {% block link %}
        {% endblock %}
    </head>
    <body>
        <header>
            <!--div class="container" style="border: 2px solid blue;"-->
            <div class="container">
                <!--div class="navbar row"-->
                {% include "navbar.html" %}
            </div>
        </header>
        
        
        <!-- if messages, hereafter a division to show them -->
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="container" style="background-color:WhiteSmoke;overflow-y:auto;">
        <ul class="list-unstyled">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        </div>
        {% endif %}
        {% endwith %}

        <!-- principal block content -->
        {% block content %}{% endblock %}

        <!-- footer -->
        {% include "footer.html" %}

        
        <!-- Core SCRIPTS - Always present - jQuery first, then Popper.js, then Bootstrap JS -->
         <!-- with jquery-3.5.0, collapse don't work in bootstrap 4 -->
        <!-- <script src="{{ url_for('static', filename='js/jquery-3.5.0.js') }}"></script> -->
        <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <!-- Custom SCRIPTS - Include with every page -->
        {% block javascript %}
        {% endblock %}
    </body>
</html>

covid/templates/footer.html
    <!--        FOOTER        -->
    <footer>
        <!--<div class="continer" style="border: 2px solid green;"> -->
        <div class="container" style="font-size:x-small;font-style:italic;">
            <hr class="soiola">
            {% if config.SITE.WSUBTITLE %}
            <div> <p> {{ config.SITE.WSUBTITLE }} </p> </div>
            {% endif %}
            <div class="container-fluid d-none d-sm-block" style="padding:0;">
                <p>
                    <a href="https://github.com/l-dfa/flask_covid-v1" target="_blank">{{ _('A web site section') }}</a>,
                    &nbsp;ver.{{ config.VER }}
                    &nbsp;{{ _('powered by') }}:
                    <a href="https://www.python.org/" target="_blank">Python</a>,
                    <a href="https://palletsprojects.com/p/flask/" target="_blank">Flask</a>,
                    <a href="https://pandas.pydata.org/" target="_blank">Pandas</a> {{ _('and') }}
                    <a href="https://matplotlib.org/" target="_blank">Matplotlib</a>
                    {% if config.SITE.WLICENSE %}
                        <span style="float:right;">
                        {{ _('Under a') }} <a rel="license" href="{{ config.SITE.WLICENSEREF }}" target="_blank">{{ config.SITE.WLICENSE }}</a>.
                        </span>
                    {% endif %}
                </p>
            </div>
        </div>
    </footer>

covid/templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="container" style="background-color:WhiteSmoke;overflow-y:auto;">
        <h3>{{ _('Time trend analysis of Covid-19 outbreak') }}</h3>
        <div>
            <p>
            {{ _('This site section is to show the time trend of Covid-19 outbreak') }}.</p>
            
            <p>
            {{ _('Here you can select one or more') }} <a href="{{ url_for('views.select') }}">{{ _('nations or continents') }}</a>
            {{ _('to compare their time trend of total cases of positive infection to the viruses') }}.
            {{ _('Please do not select too many nations, or the graph will be unreadable') }}.<br>
            {{ _('You can select a time interval to show the trend inside it')}}.
            {{ _('In this case be warned that you can') }} <i>{{ _('forget') }}</i>, {{ _('or not, data present in days before the chosen start of the time interval')}}.
            {{ _('To forget data before a given date could be useful to analize duly the trend of the infection in a specific time interval')}}.
            </p>

            <p>
            {{ _('Alternatively you can use') }} <a href="{{ url_for('views.other_select') }}">{{ _('some other query type') }}</a>.
            {{ _('Here you can check data about') }} <i>{{ _('all the world') }}</i> {{ _('as a unit') }},
            {{ _('or about the') }} <i>{{ _('N worst nations in the world') }}</i>, {{ _('and others') }}.
            {{ _('Be aware that you can select the World also as a continent in') }} <i>{{ _('nations or continents') }}</i>.<br>
            {{ _('In this windows you have the same types of controls present in') }} <i>{{ _('nations or continents') }}</i> {{ _('to build the wanted query') }}.
            </p>

            <p>
            {{ _('Data available range from') }} {{ FIRST }} {{ _('to') }} {{ LAST }} {{ _('and regard') }} {{ HOW_MANY}} {{ _('between countries and territories')}}.
            </p>

            <h4>{{ _('Reference') }}</h4>
            <div>
                <p>
                {{ _('This site uses') }} 
                <a href="https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide">{{ _('data') }}</a>
                {{ _('published by') }}
                <a href="https://www.ecdc.europa.eu/en">{{ _('European Centre for Disease Prevention and Control') }}</a>.
                
                {{ _('This Agency every day at noon updates data about the spread of
                Covid-19 disease in all the world') }}.
                {{ _('Therefore this site is updated at 13:15 CET (or CEST, when daylight saving time is in charge)') }}. 
                </p>
            </div>   
                
            <h4>{{ _('Goodbye') }}</h4>
            <div>
                <p>{{ _('Thank you to visit this site') }}. 
                {{ _('Just in case you have nothing more interesting to do, here you can') }} <a href="https://luciano.defalcoalfano.it">{{ _('read my blog') }}</a>. 
                {{ _('Most of the articles are in Italian language, some of them are translated in English language') }}.
                </p>
                
                <p>
                Enjoy. ldfa
                </p>
            </div>
            
            <hr>

            <p>
                <a data-toggle="collapse" href="#history"> <span style="border: 1px solid; border-radius: 5px;"> {{ _('click here') }} </span></a> &nbsp;
                {{ _('to show/hide history of this section') }}
            </p>
            
            <div class="collapse" id="history">
                <dl style="display: grid; grid-template-columns: max-content auto;">
                    <dt style="grid-column: 1;" >ver.1.4</dt>
                        <dd style="grid-column: 2;">- {{ _('reorganizing user interface of query criterions in "select" and "world ..."')}} </dd>
                        <dd style="grid-column: 2;">- {{ _('fast selection of last 7 and last 30 days in "time interval"')}} </dd>
                        <dd style="grid-column: 2;">- {{ _('handling the presence of a NaN data in last day table')}} </dd>
                    <dt style="grid-column: 1;" >ver.1.3</dt>
                        <dd style="grid-column: 2;">- {{ _('preserve initial cases/deaths in case of time interval')}} </dd>
                        <dd style="grid-column: 2;">- {{ _('check on "Interval" in other_select')}} </dd>
                        <dd style="grid-column: 2;">- {{ _('reorganize table about last day data')}} </dd>
                        <dd style="grid-column: 2;">- {{ _('some bug fixing')}} </dd>
                    <dt style="grid-column: 1;">ver.1.2</dt>
                        <dd style="grid-column: 2;">- {{_('UI: separating mandatory main fields (cases, deaths) from optional secondary fields (cases/day, ...)') }}</dd>
                        <dd style="grid-column: 2;">- {{_("reorganizing select UI (fields, time interval, ... on top of user's window)") }}</dd>
                        <dd style="grid-column: 2;">- {{_('adding ratio over population') }}</dd>
                        <dd style="grid-column: 2;">- {{_('adding "Worst World" query in other select') }}</dd>
                        <dd style="grid-column: 2;">- {{_('adding "Worst EU" query in other select') }}</dd>
                    <dt style="grid-column: 1;">ver.1.1</dt>
                      <dd style="grid-column: 2;">- {{_('adding field cases/day') }}</dd>
                      <dd style="grid-column: 2;">- {{_('changing denomination field d²cases_dt² to &Delta;cases/day') }}</dd>
                      <dd style="grid-column: 2;">- {{_('using bootstrap icons instead of "more info ..."') }}</dd>
                    
                    <dt style="grid-column: 1;">ver.1.0</dt>
                      <dd style="grid-column: 2;">- {{_('adding possibility to show observations about the entire World') }}</dd>
                    <dt style="grid-column: 1;">ver.08</dt>
                      <dd style="grid-column: 2;">- {{_('adding possibility to chose date interval, check them and check nations vs continents') }}</dd>
                    <dt style="grid-column: 1;">ver.07</dt>
                      <dd style="grid-column: 2;">- {{_('added a table of data values on the last day in the picture') }}</dd>
                    <dt style="grid-column: 1;">ver.06</dt>
                      <dd style="grid-column: 2;">- {{_('added a summary table of data used to build chosen observations to draw') }}</dd>
                    
                    <dt style="grid-column: 1;">ver.05</dt>
                    <dd style="grid-column: 2;">- {{_('added European Union in nations') }}</dd>
                    <dd style="grid-column: 2;">- {{_('added South, Central and North America sub continents') }}</dd>
                    <dt style="grid-column:1;">ver.04</dt>
                      <dd style="grid-column: 2;">- {{_('added the second derivative of total positive cases to show the curve concavity') }}</dd>
                      <dd style="grid-column: 2;">- {{_('a better user interface to select nations') }}</dd>
                    <dt style="grid-column: 1;">ver.03</dt>
                      <dd style="grid-column: 2;">- {{_('added the comparison between continents') }}</dd>
                    <dt style="grid-column:1;">ver.02</dt>
                      <dd style="grid-column: 2;">- {{_('user can choose what infos to plot: positive cases and/or deaths') }}</dd>
                </dl>                
            </div>

        </div>
        
    </div>
{% endblock %}

covid/templates/navbar.html

<div class="rsts-header">
  <div class="rsts-brand"> <!-- +container-fluid -->
    <a class="navbar-brand soiola" href="https://luciano.defalcoalfano.it">
        <!-- warning: use 'url_for' to get static resources, otherwise it could fail on some template(s) -->
        <img src="{{  url_for('static', filename='images/avatar.jpg') }}" alt="ldfa website" style="width:52px;height:52px;border:0;padding:0;">
    </a>
  </div>
  <div class="soiola" style="float:left;">
    <div class="container-fluid d-none d-sm-block soiola">
      <h4 class="soiola" style="text-align:center;color:DarkSlateBlue;">{{ config.SITE.WTITLE }}
      </h4>
    </div>
    <nav class="navbar navbar-default soiola">
        <div class="container-fluid">
                <ul class="list-inline">
                    <li class="list-inline-item"><a href="{{ url_for('views.index') }}">{{ _('Covid Section') }}</a>&nbsp;</li>
                    <li class="list-inline-item"><a href="https://luciano.defalcoalfano.it">Blog</a>&nbsp;</li>
                    <!-- <li class="list-inline-item"><a href="{{ url_for('views.select') }}">{{ _('Select') }}</a></li> -->
                    
                    
                    <li class="dropdown soiola list-inline-item">        <!-- Select submenu -->
                        <a class="dropdown-toggle soiola" data-toggle="dropdown" href="#">{{ _('Select') }}<span class="caret"></span></a>
                        <ul class="dropdown-menu soiola">
                            <li class="nav-item soiola">  <!-- Select submenu / Countries -->
                              <a class="nav-link soiola" href="{{ url_for('views.select') }}" style="border:0;padding:2px;">{{ _('Countries/Continents') }}</a>
                            </li>
                            <!-- <li class="divider"><hr></li> -->
                            <li class="nav-item soiola">  <!-- Select submenu / World -->
                              <a class="nav-link soiola" href="{{ url_for('views.other_select') }}" style="border:0;padding:2px;">{{ _('World ...') }}</a>
                            </li>
                        </ul>
                    </li>


                </ul>
        </div>
    </nav>
  </div>
</div>


covid/templates/select.html
{% extends "base_select.html" %}

{#
    {% block on_what_plot %}
            <div class="row">
                <div class="col-md-12">
                <p>{{_('For every selected country or continent')}}: </p>
                </div>
            </div>
    {% endblock %}
#}

{% block selection_lists %}

            <div class="row">
                <div class="col-md-3">
                    <p><span  style="font-style: italic;text-decoration: underline;">{{_('Geographical entity')}}</span> {{_('to select')}}.
                       <a data-toggle="collapse" href="#explainGeo"><span><img src="/static/images/bootstrap-icons-1.0.0/question-circle.svg" alt="" width="16" height="16" title="more_info"></span></a>
                    </p>
                <div class="collapse" id="explainGeo">
                    <p>
                    <span style="font-weight: bold;">nations</span>    {{ _('enables the box to select from countries and territories; while') }},
                    <span style="font-weight: bold;">continents</span> {{ _('enables the box to select what continent(s) to display') }}.
                    <br>
                    {{_('Continents definitions (so: what countries are in every continent) are from United Nations and/or Wikipedia')}}.
                    <br>
                    {{_('The population data in the database are from the World Bank')}}.
                    </p>
                </div>
                    <p>
                        {# {{ form.fields.label }}<br> #}
                        {{ form.context(**{ 'id':    'context',
                                            'style': 'list-style-type:none;padding:0;margin:0;',
                                          }
                                       ) }}<br>
                        {% for error in form.context.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                </div>
                <div class="col-md-6">
                    <p> <span  style="font-style: italic;text-decoration: underline;">{{ _('Countries and territories') }}</span></p>
                    <p>
                        {# {{ form.countries.label }}<br> #}
                        {{ form.countries(size=22, **{ 'id':       'nations',
                                                       'data-toggle':    'tooltip',
                                                       'data-delay': 1500,
                                                       'title':    TOOLTIP_TITLE
                                                     }
                                         ) }}<br>
                        {% for error in form.countries.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                </div>
                <div class="col-md-3">
                    <p> <span  style="font-style: italic;text-decoration: underline;">{{ _('Continents') }}</span></p>
                    <p>
                        {# {{ form.continents.label }}<br> #}
                        {{ form.continents(size=continents|length, **{ 'id':       'continents',
                                                                       'disabled': 'true',
                                                                       'data-toggle':    'tooltip',
                                                                       'data-delay': 1500,
                                                                       'title': TOOLTIP_TITLE,
                                                                       'style': 'scrollbar-width: none;',
                                                                     }
                                          ) }}<br>
                        {% for error in form.continents.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                </div>
            </div>
            
{% endblock %}


{% block other_javascript %}
    <script>
        $(function (){$('[data-toggle="tooltip"]').tooltip()} )</script>
    <script>
        $(function() {
                var in_context = $("input[name=context]:checked").val();
                if(in_context=='nations'){
                    document.getElementById('nations').disabled = false;
                    document.getElementById('continents').selectedIndex = -1
                    document.getElementById('continents').disabled = true;
                    }
                else if(in_context=='continents'){
                    document.getElementById('nations').selectedIndex = -1;
                    document.getElementById('nations').disabled = true;
                    document.getElementById('continents').disabled = false;
                    }
                }) 
    </script>
    <script>
        $(function() {
            $('#context li').click( function() {
                var in_context = $("input[name=context]:checked").val();
                console.log(in_context);
                if(in_context=='nations'){
                    document.getElementById('nations').disabled = false;
                    document.getElementById('continents').selectedIndex = -1
                    document.getElementById('continents').disabled = true;
                    }
                else if(in_context=='continents'){
                    document.getElementById('nations').selectedIndex = -1;
                    document.getElementById('nations').disabled = true;
                    document.getElementById('continents').disabled = false;
                    }
                }) })
    </script>
{% endblock %}